pub const Room = struct {
    name: []const u8,
    description: []const u8,
    items: ?[*]u16,
    //exits: []u8,
    north: ?usize,
    east: ?usize,
    south: ?usize,
    west: ?usize,
    up: ?usize,
    down: ?usize,
};

pub var rooms = [_]Room{
    Room{ // 0
        .name = "start",
        .description = "This is your bedroom. You keep forgetting to clean it...",
        .items = null,
        .north = null,
        .south = 1,
        .east = null,
        .west = null,
        .up = null,
        .down = null,
    },
    Room{ // 1
        .name = "apartment_living_room",
        .description = "This is your apartment living room.",
        .items = null,
        .north = null,
        .east = 2,
        .south = 3,
        .west = null,
        .up = null,
        .down = null,
    },
    Room{ // 2
        .name = "bathroom",
        .description = "A cute little bathroom.",
        .items = null,
        .north = null,
        .east = null,
        .south = null,
        .west = 1, // connected to living room
        .up = null,
        .down = null,
    },
    Room{ // 3
        .name = "your_apartment_entrance",
        .description = "Just outside of your apartment building.",
        .items = null,
        .north = 1,
        .east = null,
        .south = 4,
        .west = null,
        .up = null,
        .down = null,
    },
    Room{ // 4
        .name = "the_end",
        .description = "You made it!",
        .items = null,
        .north = null,
        .east = null,
        .south = 1,
        .west = null,
        .up = null,
        .down = null,
    },
};
